const $=s=>document.querySelector(s),esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let selected=1,filter='Todos',query='',zoom=.86,rx=43,rz=-13,focus=[0,0],gallery=[],galleryIndex=0;
const categories=['Todos','Parques','Compras','Aulas','Lazer/Descanso'];
const icons={'Parques':'✧','Compras':'▣','Aulas':'▤','Lazer/Descanso':'☼'};
const photoList=k=>photos[k]?.images||[],photo=k=>photoList(k)[0];
const imageMarkup=(k,cls='')=>photo(k)?`<img class="${cls}" src="${esc(photo(k).url)}" alt="${esc(places[k][0])}" loading="lazy" onerror="this.outerHTML='<div class=&quot;no-photo&quot;>Foto indisponível no momento</div>'">`:`<div class="no-photo">${esc(places[k][0])}</div>`;
function renderFilters(){ $('#filters').innerHTML=categories.map(c=>`<button class="${filter===c?'active':''}" aria-pressed="${filter===c}" data-filter="${c}">${c==='Lazer/Descanso'?'Lazer':c}</button>`).join(''); }
function renderDays(){let list=days.filter(d=>(filter==='Todos'||d.cats.includes(filter))&&(`${d.title} ${d.activities.join(' ')} ${d.places.map(k=>places[k][0]).join(' ')} ${d.day}/10`.normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().includes(query)));$('#days').innerHTML=list.length?list.map(d=>`<button class="day ${selected===d.index?'active':''}" data-day="${d.index}" aria-current="${selected===d.index?'date':'false'}"><span class="daynum">${String(d.day).padStart(2,'0')}<small>OUT</small></span><span class="day-info"><small>${d.weekday.toUpperCase()}</small><strong>${esc(d.title)}</strong></span><span class="day-symbol">${icons[d.cats.at(-1)]}</span></button>`).join(''):'<div class="empty">Nenhum dia encontrado. Tente outro lugar ou filtro.</div>';}
function xy(k){let p=places[k];return [(p[2]+81.63)/.37*900,(28.57-p[1])/.30*560];}
function mapTransform(){ $('#world').style.transform=`translate(${focus[0]}px,${focus[1]}px) rotateX(${rx}deg) rotateZ(${rz}deg) scale(${zoom})`; }
const mapped=Object.keys(places).filter(k=>places[k][1]);
function renderPins(){let d=days[selected];$('#pins').innerHTML=mapped.map(k=>{let [x,y]=xy(k);let short={airport:'MCO',wonder:'WonderWorks',icon:'ICON Park',epic:'Epic Universe',universal:'Universal',vineland:'Vineland',millenia:'Millenia',springs:'Disney Springs',magic:'Magic Kingdom',outlets:'Int. Outlets',fort:'Fort Wilderness',celebration:'Celebration',oldtown:'Old Town',floridamall:'Florida Mall',kia:'Kia Center'}[k]||places[k][0];return `<button class="pin ${d.places.includes(k)?'selected':'compact'}" style="left:${x}px;top:${y}px" data-pin="${k}" aria-label="Explorar ${esc(places[k][0])}"><span>◈</span><b>${short}</b></button>`}).join('');}
function selectDay(i,move=true){selected=Math.max(0,Math.min(15,i));let d=days[selected];$('#progress-label').textContent=`${selected+1} / 16 dias`;$('#progress').value=selected+1;renderDays();renderPins();let key=d.places.find(k=>places[k][1]);if(move){if(key){let [x,y]=xy(key);focus=[(450-x)*.25,(280-y)*.14];}else focus=[0,0];mapTransform();}$('#map-caption').textContent=key?places[key][0]:'Dia livre · acomodação a definir';$('#detail').innerHTML=`<div class="detail-header"><div><div class="eyebrow">DIA ${String(selected+1).padStart(2,'0')} &nbsp; / &nbsp; ${String(d.day).padStart(2,'0')} OUT · ${d.weekday.toUpperCase()}</div><h2>${esc(d.title)}</h2></div><div class="nav-days"><button data-prev ${selected===0?'disabled':''} aria-label="Dia anterior">‹</button><button data-next ${selected===15?'disabled':''} aria-label="Próximo dia">›</button></div></div><div class="day-body"><button class="hero-photo" data-open="${d.places[0]}" aria-label="Ver fotos e detalhes de ${esc(d.title)}">${imageMarkup(d.places[0])}<span class="photo-count">▧ &nbsp; Explorar fotos</span><div class="hero-copy"><span>ORLANDO · OUTUBRO 2026</span><h3>${esc(d.tagline)}</h3><small>⌖ &nbsp; ${esc(places[d.places[0]][0])}</small></div></button><div class="agenda"><div class="agenda-top"><h3>O plano do dia</h3><div class="badges">${d.cats.map(c=>`<span class="badge">${c==='Lazer/Descanso'?'Lazer':c}</span>`).join('')}</div></div>${d.activities.map((a,j)=>`<button class="activity" data-open="${d.places[Math.min(j,d.places.length-1)]}"><span class="bullet">${j+1}</span><span>${esc(a)}</span></button>`).join('')}<div class="note"><b>ⓘ &nbsp; Para ter em mente</b>${esc(d.note)}</div></div></div><div class="places-heading"><h3>Paradas & descobertas</h3><span>${d.places.length} ${d.places.length===1?'local':'locais'} no roteiro</span></div><div class="place-grid">${d.places.map(k=>`<button class="place-card" data-open="${k}">${imageMarkup(k)}<div><strong>${esc(places[k][0])}</strong><small>Fotos, detalhes e localização &nbsp; ↗</small></div></button>`).join('')}</div>`;}
function openPlace(k){const d=days[selected],p=places[k];gallery=[...photoList(k),...d.places.filter(key=>key!==k).flatMap(key=>photoList(key))];galleryIndex=0;$('#modal-content').innerHTML=`<div class="modal-gallery">${gallery.length?`<img id="gallery-image" src="${esc(gallery[0].url)}" alt="${esc(p[0])}"><div class="gallery-nav"><button id="gallery-prev" aria-label="Foto anterior">‹</button><span id="gallery-count">1 / ${gallery.length}</span><button id="gallery-next" aria-label="Próxima foto">›</button></div>`:`<div class="no-photo">Fotos indisponíveis no momento</div>`}</div><div class="modal-inner"><div class="eyebrow">${String(d.day).padStart(2,'0')} DE OUTUBRO · ${d.weekday.toUpperCase()}</div><h2>${esc(p[0])}</h2><p>${esc(d.tagline)}</p><ul>${d.activities.map(a=>`<li>${esc(a)}</li>`).join('')}</ul><div class="note"><b>Observações do roteiro</b>${esc(d.note)}</div>${!p[1]?'<p>Unidade ou endereço a definir com o grupo. A busca abaixo mostra opções, não um destino confirmado.</p>':''}<a class="map-link" href="https://www.google.com/maps/search/?api=1&query=${encodeURIComponent(p[0]+(p[1]?' '+p[1]+','+p[2]:' Orlando Florida'))}" target="_blank" rel="noopener">Abrir no Google Maps</a>${k!=='relax'?`<iframe title="Mapa de ${esc(p[0])}" loading="lazy" referrerpolicy="no-referrer-when-downgrade" src="https://maps.google.com/maps?q=${encodeURIComponent(p[0]+' Orlando Florida')}&output=embed"></iframe>`:''}<p class="source">${gallery.length?`Foto: <a id="photo-source" href="${esc(gallery[0].source)}" target="_blank" rel="noopener">ver fonte original</a>. Imagens representativas; aparência e programação podem mudar.`:''}</p></div>`;$('#modal').showModal();}
function turnGallery(step){if(!gallery.length)return;galleryIndex=(galleryIndex+step+gallery.length)%gallery.length;$('#gallery-image').src=gallery[galleryIndex].url;$('#gallery-image').alt=gallery[galleryIndex].label||'';$('#gallery-count').textContent=`${galleryIndex+1} / ${gallery.length}`;$('#photo-source').href=gallery[galleryIndex].source;}
document.addEventListener('click',e=>{let b=e.target.closest('button');if(!b)return;if(b.dataset.day!==undefined)selectDay(+b.dataset.day);if(b.dataset.filter){filter=b.dataset.filter;renderFilters();renderDays();}if(b.dataset.open)openPlace(b.dataset.open);if(b.dataset.pin){let k=b.dataset.pin,i=days.findIndex(d=>d.places.includes(k));if(i>=0)selectDay(i);openPlace(k);}if(b.hasAttribute('data-prev'))selectDay(selected-1);if(b.hasAttribute('data-next'))selectDay(selected+1);if(b.id==='gallery-prev')turnGallery(-1);if(b.id==='gallery-next')turnGallery(1);});
$('#search').addEventListener('input',e=>{query=e.target.value.normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase();renderDays();});
$('#theme').onclick=()=>{document.body.classList.toggle('light');try{localStorage.setItem('orlando-theme',document.body.classList.contains('light')?'light':'dark')}catch{};$('#theme').textContent=document.body.classList.contains('light')?'☾':'☼'};try{if(localStorage.getItem('orlando-theme')==='light')document.body.classList.add('light')}catch{}
$('#modal .close').onclick=()=>$('#modal').close();$('#modal').addEventListener('click',e=>{if(e.target===$('#modal'))$('#modal').close()});$('#zoomin').onclick=()=>{zoom=Math.min(1.5,zoom+.12);mapTransform()};$('#zoomout').onclick=()=>{zoom=Math.max(.45,zoom-.12);mapTransform()};$('#reset').onclick=()=>{zoom=innerWidth<700?.65:.86;rx=43;rz=-13;focus=[0,0];mapTransform()};let drag=null;$('#scene').addEventListener('pointerdown',e=>{if(e.target.closest('button'))return;drag={x:e.clientX,y:e.clientY,rz,rx};$('#scene').setPointerCapture(e.pointerId)});$('#scene').addEventListener('pointermove',e=>{if(!drag)return;rz=drag.rz+(e.clientX-drag.x)*.12;rx=Math.max(15,Math.min(65,drag.rx-(e.clientY-drag.y)*.12));mapTransform()});['pointerup','pointercancel'].forEach(n=>$('#scene').addEventListener(n,()=>drag=null));document.addEventListener('pointermove',e=>{if(e.pointerType==='touch'||matchMedia('(prefers-reduced-motion:reduce)').matches)return;let card=e.target.closest('.place-card');if(!card)return;const r=card.getBoundingClientRect();card.style.transform=`perspective(700px) rotateY(${((e.clientX-r.left)/r.width-.5)*8}deg) rotateX(${(.5-(e.clientY-r.top)/r.height)*8}deg)`;});document.addEventListener('pointerout',e=>{let card=e.target.closest('.place-card');if(card&&!card.contains(e.relatedTarget))card.style.transform=''});if(innerWidth<700)zoom=.65;renderFilters();selectDay(1);
