const places={
airport:['Orlando International Airport',28.4312,-81.3081],walmart:['Walmart Supercenter Orlando',null,null],wonder:['WonderWorks Orlando',28.4336,-81.4718],pointe:['Pointe Orlando',28.4326,-81.4697],icon:['ICON Park',28.4439,-81.4695],drive:['International Drive',28.437,-81.471],epic:['Universal Epic Universe',28.4398,-81.4478],universal:['Universal Studios Florida',28.475,-81.468],islands:['Islands of Adventure',28.471,-81.472],vineland:['Orlando Vineland Premium Outlets',28.387,-81.493],cinema:['Touchstar Cinemas Southchase 7',28.379,-81.405],millenia:['The Mall at Millenia',28.485,-81.432],cheese:['The Cheesecake Factory — Millenia',28.485,-81.432],johnny:['Johnny Rockets',null,null],springs:['Disney Springs',28.371,-81.518],disney:['World of Disney',28.371,-81.514],magic:['Magic Kingdom',28.4186,-81.5812],outlets:['Orlando International Premium Outlets',28.474,-81.451],ford:["Ford’s Garage",null,null],fort:["Fort Wilderness — Chip ’n’ Dale’s Campfire",28.409,-81.558],gideon:["Gideon’s Bakehouse — Disney Springs",28.371,-81.519],celebration:['Celebration',28.318,-81.542],oldtown:['Old Town Kissimmee',28.33,-81.515],relax:['Descanso na acomodação',null,null],floridamall:['The Florida Mall',28.446,-81.395],target:['Target',null,null],kia:['Kia Center',28.5392,-81.3839]};
const days=[
[2,'Chegada em Orlando',['Lazer/Descanso'],['airport','walmart'],['Chegada em Orlando e deslocamento para a acomodação.','Organização do grupo e acomodação.','Walmart para compras iniciais e itens necessários para a estadia.','Jantar e descanso.'],'A unidade do Walmart será escolhida conforme a acomodação.','Chegar, respirar e começar.'],
[3,'International Drive',['Lazer/Descanso'],['wonder','pointe','icon','drive'],['WonderWorks — Casa Invertida.','Pointe Orlando e passeio pela International Drive.','ICON Park e tempo para conhecer a região.'],'Dia propositalmente mais leve após a chegada, sem sobrecarregar o grupo antes dos parques.','Um primeiro encontro com Orlando.'],
[4,'Epic Universe',['Parques'],['epic'],['Dia inteiro no Epic Universe.','Programação dedicada ao parque.'],'Dia de parque fixo.','Um universo inteiro de possibilidades.'],
[5,'Universal + Islands of Adventure',['Parques'],['universal','islands'],['Dia inteiro nos parques Universal Studios Florida e Islands of Adventure.','Experiência entre os dois parques conforme os ingressos e a programação do grupo.'],'Dia de parque fixo. Confira se o ingresso permite a visita aos dois parques e o Hogwarts Express.','Entre o cinema e a aventura.'],
[6,'Aula + Vineland Outlets',['Aulas','Compras'],['vineland'],['Aula pela manhã.','Orlando Vineland Premium Outlets no período da tarde.','Jantar na região e retorno para descanso.'],'A proposta evita juntar Vineland e Downtown Orlando no mesmo dia, reduzindo deslocamentos desnecessários.','Novas palavras, novas descobertas.'],
[7,'Aula + cinema',['Aulas','Lazer/Descanso'],['cinema'],['Aula pela manhã.','Tarde livre para descanso, organização ou atividade leve.','Cinema à noite — sugestão: Touchstar Cinemas.'],'Valor e promoção do ingresso a confirmar. Southchase 7 é uma sugestão de unidade; confirme com o grupo.','Uma pausa e uma boa história.'],
[8,'Aula + Mall at Millenia',['Aulas','Compras'],['millenia','cheese','johnny'],['Aula pela manhã.','The Mall at Millenia — passeio e compras.','Jantar na região.'],'Sugestões: The Cheesecake Factory ou Johnny Rockets. Confirme a unidade do restaurante.','Um pouco de estilo no caminho.'],
[9,'Aula + Disney Springs',['Aulas','Lazer/Descanso'],['springs','disney'],['Aula pela manhã.','Disney Springs no período da tarde e noite.','Passeio, lojas e opções de alimentação.'],'Combine um ponto de encontro com o grupo antes de explorar as lojas.','A magia também mora nos detalhes.'],
[10,'Magic Kingdom',['Parques'],['magic'],['Dia inteiro no Magic Kingdom.','Programação dedicada ao parque.'],'Dia de parque fixo.','O dia de viver a magia.'],
[11,'International Premium Outlets',['Compras'],['outlets','ford'],['Dia de compras no Orlando International Premium Outlets.','Tempo livre para lojas e alimentação.'],'Sugestão de refeição: Ford’s Garage, conforme a logística do dia. Unidade a definir.','Tempo para encontrar seus favoritos.'],
[12,'Aula + Fort Wilderness',['Aulas','Lazer/Descanso'],['fort','gideon'],['Aula pela manhã.','Período para descanso e preparação para a programação da noite.','Fort Wilderness — Chip ’n’ Dale’s Campfire Sing-A-Long e experiência de s’mores na fogueira.'],'Gideon’s Bakehouse pode entrar como parada opcional, conforme tempo e logística. Confirme acesso e programação da fogueira.','Uma noite para guardar na memória.'],
[13,'Aula + Celebration + Old Town',['Aulas','Lazer/Descanso'],['celebration','oldtown'],['Aula pela manhã.','Celebration — passeio pela região.','Old Town Kissimmee — passeio e atrações no fim da tarde e noite.'],'Celebration e Old Town formam uma combinação prática por estarem no eixo de Kissimmee.','Ruas charmosas e luzes de fim de tarde.'],
[14,'Aula + tarde livre',['Aulas','Lazer/Descanso'],['relax'],['Aula pela manhã.','Tarde livre para descanso, compras pontuais ou atividade de interesse do grupo.'],'Esse período fica intencionalmente mais leve para descanso durante a segunda semana. Acomodação ainda não informada no roteiro.','Desacelerar também faz parte.'],
[15,'Aula + Florida Mall + Target',['Aulas','Compras'],['floridamall','target'],['Aula pela manhã.','Florida Mall — passeio e compras.','Target, conforme tempo e necessidade do grupo.'],'A unidade da Target será definida conforme o trajeto do grupo.','As últimas descobertas nas lojas.'],
[16,'Formatura + NBA',['Aulas','Lazer/Descanso'],['kia'],['Último dia de aula.','Cerimônia de formatura e entrega dos certificados.','Preparação e deslocamento para o Kia Center.','19h — Orlando Magic × Miami Heat, conforme o roteiro fornecido; confirmar na programação oficial.'],'Programação da cerimônia será alinhada com a escola; o restante do dia será mantido mais enxuto por causa do jogo. Data, adversário e horário do jogo a confirmar.','Conquistas de dia. Emoção à noite.'],
[17,'Despedida de Orlando',['Lazer/Descanso'],['airport'],['Manhã livre para organização das malas e últimos preparativos.','Almoço especial de despedida.','Retorno à acomodação, conferência de bagagens e organização do grupo.','17h — saída para o aeroporto.'],'17h é o horário de saída para o aeroporto, não o horário do voo.','Na mala, muito mais que lembranças.']
].map((d,i)=>({day:d[0],title:d[1],cats:d[2],places:d[3],activities:d[4],note:d[5],tagline:d[6],index:i,weekday:new Intl.DateTimeFormat('pt-BR',{weekday:'long',timeZone:'UTC'}).format(new Date(Date.UTC(2026,9,d[0])))}));
